#ifndef SYSTEMCONTROLLERRESULT_H
#define SYSTEMCONTROLLERRESULT_H

enum class TaskResult
{
    SUCCESS,
    FAILURE,
    CANCELLED,
    INVALID,
    NOT_IMPLMENTED
};

#endif //SYSTEMCONTROLLERRESULT_H
